const Employees = [
  {
    id: "1",
    firstname: "Parth",
    lastname: "Dave",
    email: "parth@gmail.com",
    phone: "8612536985",
    gender: "Male",
    department: "PHP",
    skills: ["App Development", "Communication", "Backend Technology"],
    about: "My name is Parth.",
  },
  {
    id: "2",
    firstname: "Raj",
    lastname: "shah",
    email: "raj@gmail.com",
    phone: "7896164585",
    gender: "Male",
    department: "Mobile",
    skills: ["Frontend Technology", "Finance", "Recruitment"],
    about: "My name is Raj.",
  },
  {
    id: "3",
    firstname: "Yasha",
    lastname: "Thakur",
    email: "yasha@gmail.com",
    phone: "7789562389",
    gender: "Female",
    department: ".NET",
    skills: ["Programming", "Communication", "Optimization"],
    about: "My name is Yasha.",
  },
  {
    id: "4",
    firstname: "Bhavya",
    lastname: "Patel",
    email: "Bhavya@gmail.com",
    phone: "7678526366",
    gender: "Female",
    department: "Account",
    skills: ["Finance", "Recruitment", "Optimization"],
    about: "My name is Bhavya.",
  },
  {
    id: "5",
    firstname: "Sahil",
    lastname: "Patel",
    email: "Sahil@gmail.com",
    phone: "7678526366",
    gender: "Male",
    department: "Account",
    skills: ["Recruitment"],
    about: "My name is Sahil",
  },
  {
    id: "6",
    firstname: "Abhi",
    lastname: "Patel",
    email: "abhi@gmail.com",
    phone: "8547963225",
    gender: "Male",
    department: ".NET",
    skills: ["Programming", "Finance"],
    about: "My name is Abhi",
  },
  {
    id: "7",
    firstname: "Jhon",
    lastname: "Smith",
    email: "Jhon@gmail.com",
    phone: "7562581254",
    gender: "Male",
    department: "SEO",
    skills: ["Optimization", "Recruitment"],
    about: "My name is Jhon",
  },
  {
    id: "8",
    firstname: "Rachel",
    lastname: "Nagarajan",
    email: "Rachel@gmail.com",
    phone: "9912581254",
    gender: "Female",
    department: "PHP",
    skills: ["Finance", "Recruitment"],
    about: "My name is Rachel",
  },
  {
    id: "9",
    firstname: "Leelawati",
    lastname: "Kulkarni",
    email: "LeelaWati@gmail.com",
    phone: "8952581254",
    gender: "Female",
    department: ".NET",
    skills: ["Programming", "Finance"],
    about: "My name is Leelawati",
  },
  {
    id: "10",
    firstname: "Siddharth",
    lastname: "Usman",
    email: "Siddharth@gmail.com",
    phone: "8823681254",
    gender: "Male",
    department: "Account",
    skills: ["Backend Technology", "Finance", "Recruitment"],
    about: "My name is Jhon",
  },
];

export default Employees;

