import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Todo from "./ToDo";
import axios from "axios";
import { useEffect, useState } from "react";

export default function Home() {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (title == "") {
      alert("title is required");
    } else if (description == "") {
      alert("description is required");
    } else {
      try {
        let res = await axios.post("/api/add", {
          title: title,
          description: description,
        });
      } catch (error) {
        console.log(error);
      }
    }
  };

  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.description}>
          <nav
            className="navbar navbar-expand-md navbar-dark fixed-top bg-dark"
            style={{ height: "10%" }}
          >
            <h2 style={{ color: "white" }}>Todo App</h2>
          </nav>
        </div>
        <br />
        <br />
        <br />
        <form className="needs-validation">
          <div
            style={{
              display: "flex",
              alignItems: "center",
              flexDirection: "column",
            }}
          >
            <h3>Add Todo</h3>

            <input
              type="text"
              name="title"
              id="title"
              className="form-control"
              placeholder="Enter Your title"
              style={{ width: "300px", marginBottom: "10px" }}
              onChange={(e) => setTitle(e.target.value)}
            />

            <textarea
              className="form-control"
              name="description"
              placeholder="Enter your description"
              style={{ width: "300px", resize: "none", marginBottom: "10px" }}
              onChange={(e) => setDescription(e.target.value)}
            />
            <button
              type="button"
              className="btn btn-dark"
              onClick={handleSubmit}
            >
              Add
            </button>
          </div>
        </form>
        <br />
        <Todo />
      </main>
    </>
  );
}
